### PR TITLE
workaround for issue #7 on cygwin 64

### PR DESCRIPTION
**Pull request by wscheele**
2 pass GetTokenInformation to prevent Errno::ENOENT. read uint when result length == 4 to prevent 'Memory access offset=0 size=8 is out of bounds (IndexError)'

resulting workaround after encountering issue #7

### CODE REVIEW

**Comment by djberg96** [comment]
You're right that we should check ReturnLength, but it should only be two-pass if necessary. Wouldn't this work?

      rlength = rl.read_ulong

      if rlength > te.size
        te = FFI::MemoryPointer.new(rlength)
        rl.clear

        bool = GetTokenInformation(
          token,
          :TokenElevation,
          te,
          te.size,
          rl
        )
      end

**Comment by wscheele** [comment]
hi @djberg96 , that should probably work as well indeed.
i've actually 'facter'ed out my dependency on win32-security, so don't really need the fix. but thought i'd send a PR with the code changes that made it work for me, being for the benefit of mr kite...

**Comment by djberg96** [comment]
@wscheele Ok, closing this one then, thanks.

**Comment by djberg96** [comment]
@wscheele My approach ended up not working, but yours did. If you rebase then I will merge it.

**Comment by djberg96** [comment]
NM, didn't require a rebase apparently.

**Pull request merged**
